services:
    bordeux.geoname.import.timezone:
        class: Bordeux\Bundle\GeoNameBundle\Import\TimeZoneImport
        arguments: ["@doctrine"]
        public: true

    bordeux.geoname.import.administrative:
        class: Bordeux\Bundle\GeoNameBundle\Import\AdministrativeImport
        arguments: ["@doctrine"]
        public: true

    bordeux.geoname.import.geoname:
        class: Bordeux\Bundle\GeoNameBundle\Import\GeoNameImport
        arguments: ["@doctrine"]
        public: true


    bordeux.geoname.import.country:
        class: Bordeux\Bundle\GeoNameBundle\Import\CountryImport
        arguments: ["@doctrine"]
        public: true

    bordeux.geoname.import.hierarchy:
        class: Bordeux\Bundle\GeoNameBundle\Import\HierarchyImport
        arguments: ["@doctrine"]
        public: true


    #auto register all commands
    bordeux.geoname.command.import:
        class: Bordeux\Bundle\GeoNameBundle\Command\ImportCommand
        tags:
              - { name: console.command }