language: php

sudo: true
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  include:
    - php: 7.4
      env: SYMFONY_VERSION="5.*"
    - php: 8.0
      env: SYMFONY_VERSION="5.*"

env:
  global:
    - deps=no
    - DATABASE_NAME="my_project"
    - DATABASE_DRIVER="pdo_mysql"
    - PGUSER=postgres
    - PGDATABASE=postgres

  matrix:
    - DATABASE_DRIVER="pdo_pgsql"
    - DATABASE_DRIVER="pdo_mysql"

before_install:
  - mysql -e "CREATE DATABASE $DATABASE_NAME ;"
  - sudo service postgresql stop
  - sudo service postgresql start 9.6
  - psql -c 'create database '"$DATABASE_NAME"';' -U postgres
  - if [ "$DATABASE_DRIVER" == "pdo_pgsql" ]; then export DATABASE_PORT=5432; fi;
  - if [ "$DATABASE_DRIVER" == "pdo_pgsql" ]; then export DATABASE_USER="postgres"; fi;
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
  - ./Tests/Resources/app/console doctrine:schema:update --force

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml


after_script:
    - php ./vendor/bin/coveralls -v
